# Generated by Django 4.1.7 on 2023-11-08 10:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("items", "0002_alter_category_options_item"),
        ("communicate", "0002_conversationmessage_content"),
    ]

    operations = [
        migrations.RenameModel(old_name="Conversation", new_name="ConversationU",),
    ]
